apiVersion: apps/v1
kind: Deployment
metadata:
  name: theia-deployment
  labels:
    app: theia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theia
  template:
    metadata:
      labels:
        app: theia
    spec:
      containers:
      - name: theia
        image: kdvolder/k8s-theia:latest
        ports:
        - containerPort: 3000
