platform: linux
image_resource:
  type: docker-image
  source:
    repository: kdvolder/sts4-build-env
run:
  path: sts4/concourse/tasks/unpack.sh
inputs:
- name: sts4
- name: in
outputs:
- name: out
